Added support for multiple streamdecks & config file flag
unix-streamdeck/streamdeckd pull request #10
Opened 2021-05-13 21:50 UTC by The-Jonsey

- Added `-config` flag to specify a path to a config file on launch
- Added support for multiple streamdecks

2021-05-20 13:10 UTC, andydotxyz requested changes

2021-05-20 13:11 UTC, andydotxyz commented on main.go
> +			go Listen(dev)
If this is desirable we at least should have a time delay so it's not spinning a CPU

2021-05-30 00:26 UTC, The-Jonsey commented on main.go
> +			go Listen(dev)
Added a time delay to reduce CPU usage, as it is desired for streamdeckd to always be listening for new devices

2021-09-12 15:30 UTC, andydotxyz reviewed
Nice, works for me - just a comment inline.
One other thought is that my old config didn't work (previewed OK but buttons didn't action) - not sure if that is a problem or not, I reset and it worked fine.

2021-09-12 15:30 UTC, andydotxyz commented on interface.go
> +				deckInfo = sDInfo[i]
In other places you exit with error if there is no deck found. Will just going ahead here not cause a crash?

2021-09-12 16:40 UTC, merged